# Generated by Django 3.1.7 on 2022-08-03 23:23

from django.db import migrations, models
import django.db.models.deletion
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=kanban.models.one_week_hence)),
                ('category', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precisa ser feito')], default='importante', max_length=25)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.column')),
            ],
        ),
    ]
